### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kmpelectronics** [piotrek-k/generator-dotnetcore-angular2-starterkit#5]
I can't install this template. The error is:

npm WARN Angular2Spa@0.0.0 No license field.
'bower' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\generators\app\index.js:140
                        callback: function () { afterInstallingDependencies(context, this.props); }
                                                                                         ^

TypeError: Cannot read property 'props' of undefined
    at installDependencies.callback (C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\generators\app\index.js:140:90)
    at C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\node_modules\async\lib\async.js:726:13
    at C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\node_modules\async\lib\async.js:52:16
    at done (C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\node_modules\async\lib\async.js:241:17)
    at C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\node_modules\async\lib\async.js:44:16
    at ChildProcess.<anonymous> (C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\node_modules\async\lib\async.js:723:17)
    at ChildProcess.<anonymous> (C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\node_modules\async\lib\async.js:167:37)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at ChildProcess.cp.emit (C:\Users\Plamen\AppData\Roaming\npm\node_modules\generator-dotnetcore-angular2-starterkit\node_modules\cross-spawn-async\lib\enoent.js:33:37)

**Comment by piotrek-k** [comment]
Hi.
Thanks for reporting this issue. I can't believe there are still some errors, I've tested it thousand times before publishing ;(

I don't have time now to push an update, but I see possible fix for this issue:

I'm not sure if it will work, but try it if you want:
1. Go to place where you keep installation files of this generator. In my case, I found it here: `C:\Program Files\nodejs\node_modules\generator-dotnetcore-angular2-starterkit\generators\app`
2. Find there equivalent of this file: [index.js](https://github.com/piotrek-k/generator-dotnetcore-angular2-starterkit/blob/master/generators/app/index.js)
3. Find line that was mentioned in error: [it should look like this](https://github.com/piotrek-k/generator-dotnetcore-angular2-starterkit/blob/master/generators/app/index.js#L140)
4. Change `callback: function () { afterInstallingDependencies(context, this.props); }` to `callback: function () { afterInstallingDependencies(context, context.props); }` or `callback: function () { afterInstallingDependencies(context); }`
5. Run generator again.

Please, let me know if it worked

**Comment by kmpelectronics** [comment]
Thank you for fast response.
And two fixes works. But after start yo I switch of nmp-cashing and build project.
